name: first-pipeline
on:
   push:
    branches: ["main"]
   workflow_dispatch:
jobs:
  first-job:
    name: "My first job."
    runs-on: ubuntu-latest
    steps:
      - name: "My first action."
        run: echo "Hello World !!!"
      - name: "Second action."
        run: |
          echo " You created your first workflow."
          echo " Congratulations"
      - name: "Script Python."
        run: |
          variavel = "Hello Monteiro, my best friend"
          print(variavel)
        shell: python
        
  second-job:
    name: "Installation of the environment NodeJS."
    runs-on: ubuntu-latest
    steps:
      - name: "Verification actual version NodeJS."
        run: node --version
      - name: "Definition of version."
        uses: actions/setup-node@v4
        with:
         node-version: '20.19.6'
      - name: "Verification actual version NodeJS after installation."
        run: node --version
      
      
      
    
   
  
  
        
          
      
          
    
    
